################################################################################
# This Dockerfile was Written by Hyuk Ji on 2023/06/20.
#
#   Ubuntu Version : 22.04 LTS
#   ROS 2.0 Version: Humble
#
################################################################################

################################################################################
# Base Image
FROM ubuntu:22.04

################################################################################
# Set Non-Interactively
ENV DEBIAN_FRONTEND=noninteractive

################################################################################
# Changed Mirror Server from archive.ubuntu.com to kr.archive.ubuntu.com
RUN sed -i 's/archive.ubuntu.com/ftp.daumkakao.com/g' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/ftp.daumkakao.com/g' /etc/apt/sources.list

################################################################################
# Update and Upgrade System Packages
RUN apt-get update && \
    apt-get upgrade -y

################################################################################
# Install Dependencies
RUN apt-get update && apt-get -y install apt-utils curl sudo unzip tree lsb-release python3-pip python3-setuptools wget gnupg lsb-release locales

################################################################################
# Install ROS2 Humble on Ubuntu 22.04
RUN locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(grep -oP 'UBUNTU_CODENAME=\K\w+' /etc/os-release) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    apt-get update && \
    apt-get install -y ros-humble-desktop ros-humble-ros-base ros-dev-tools

################################################################################
# Set-up ROS2 Humble Environment
ENV LANG=en_US.UTF-8
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

################################################################################
# Install Additional Packages
RUN apt-get install -y git vim python3-colcon-common-extensions python3-vcstool

################################################################################
# Container Entry Point
CMD ["/bin/bash"]

################################################################################
# End
